replicaCount: 1
namespace: hello-dev
selector:
  app: hello-demo-app

image:
  repository: samer955/hello-app
  pullPolicy: IfNotPresent
  tag: "v1"

env:
  helloEnv: "HelmChart"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []
