replicaCount: 1
namespace: hello-prod
selector:
  app: hello-demo-app

image:
  repository: samer955/hello-app
  pullPolicy: IfNotPresent
  tag: "v1"

env:
  helloEnv: "from prod values --branch test"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
