apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/samer955/simple-hello.git
    path: demo-hello-chart
    targetRevision: feat/test-branch
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: hello-app
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://localhost:8443/repository/myhelmrepo/
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: helm
  url: https://localhost:8443/repository
  password: admin
  username: admin