name: pipeline

on:
  push:
    branches: ['main']

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: test-repository
  IMAGE_TAG: ${{ github.sha }}
  

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Code
      run: go build -v ./...

    - name: Test Code
      run: go test -v ./...

  BUILD_AND_PUBLISH:
    needs: Testing
    runs-on: ubuntu-latest
    steps: 
    - name: upload image to ECR
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        registry: ${{ secrets.AWS_REGISTRY }}
        repo: ${{ env.ECR_REPOSITORY }}
        region: ${{ env.AWS_REGION }}
        tags: latest,${{ github.run_number }}
        daemon_off: false
        dockerfile: ./Dockerfile
        context: .




    

